### ISSUE TITLE
Bringing up Action menu breaks Chromecast connection

### ISSUE THREAD

**Issue by CiNcH83** [CiNcH83/sony_atv#43]
Adjusting picture settings is essential for Chromecast as video frame rate can be anything (24p/25p/30p and multiples), requiring Motionflow frame interpolation for consistently smooth video playback.

(Same happens when bringing up _Discover_ menu.)

**Comment by JonSnow88** [comment]
This is fixed with the October Android update, at least for my 900E.

Action menu also works in YouTube
