### ISSUE TITLE
Missing apps after disabling Featured Apps shelf

### ISSUE THREAD

**Issue by CiNcH83** [CiNcH83/sony_atv#7]
After [disabling the flawed Featured Apps shelf](https://www.reddit.com/r/bravia/comments/40ozx6/howto_remove_featured_apps_section_and_sony/) and a subsequent reboot, most apps appear in the Apps shelf. Some, like for example Rakuten TV, are missing though.

**Comment by CiNcH83** [comment]
Those services (like Rakuten TV) are no Android TV apps but run via browser.

**Comment by kamilbrk** [comment]
For anyone interested, @hoshsadiq was kind enough to build an app that adds back four UK apps to leanback launcher via running webviews through `com.sony.dtv.hbbtvlauncher`.

https://github.com/hoshsadiq/bravia-youview-player-launchers

Just thought it's worth mentioning.
